FROM alpine:3.19

# Install Nginx and Tailscale
RUN apk add --no-cache nginx tailscale

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
